### ISSUE TITLE
Load more gracefully 

### ISSUE THREAD

**Issue by katiemthom** [mbyczkowski/lacocina#158]
<img width="1277" alt="screen shot 2016-11-23 at 1 42 24 pm" src="https://cloud.githubusercontent.com/assets/4976125/20580759/2cf31f16-b189-11e6-9b2a-8ca58cc7b77d.png">

Right now the page looks like this as it loads.

**Comment by mbyczkowski** [comment]
I think we got most of this covered with #159 and #160. Let's reopen if we think there's still a problem.
