### ISSUE TITLE
Volunteer Form broken 

### ISSUE THREAD

**Issue by lmramirez** [mbyczkowski/lacocina#173]
Reported by a coworker of mine who is also interested in helping out, clicking on the Volunteer Form button yields this error: 

![screen shot 2017-05-02 at 10 54 00 am](https://cloud.githubusercontent.com/assets/1825328/25631597/c1500e02-2f25-11e7-845a-88317acaa39f.png)

**Comment by abyczkowska** [comment]
https://lacocina-sf.formstack.com/forms/la_cocina_volunteer_application_copy 
link to the form 
we need this asap!
@lmramirez @mbyczkowski

**Comment by lmramirez** [comment]
@abyczkowska just opened a PR for it, works for me locally, don't know if someone wants to give it another test before merging
