### ISSUE TITLE
list of businesses on the home page

### ISSUE THREAD

**Issue by mbyczkowski** [mbyczkowski/lacocina#2]
In zeplin, there's a list of businesses (with placeholder for logos) that need to be updated.
- [x] use real logos
- [x] show tooltip with basic info on click

**Comment by mbyczkowski** [comment]
@mhgump I have uploaded new logos (touched up by @abyczkowska). Now, we just need to add some tooltips - initially, we just need a name and a link to their websites (could be 'fake' urls first and we can ask La Cocina for proper links)

**Comment by mhgump** [comment]
Is it okay to leave the tooltips on hover or should I work on making them on click?

**Comment by mbyczkowski** [comment]
We have tooltips now, too. Let's close this issue and we can open a new one to track any improvements, etc.
