### ISSUE TITLE
add load for the donation widget

### ISSUE THREAD

**Issue by mbyczkowski** [mbyczkowski/lacocina#25]
that widget is an iframe and probably there's much we can do, but it looks weird that there's a whitespace until that iframe is loaded. Maybe we can add a loader in the background that gets covered up by the iframe when it's loaded?

**Comment by mbyczkowski** [comment]
We have the loader now and it's a nice SVG, so that's great 👍 

@mhgump The loader seems a bit too big (and maybe we can also have a non-white background when showing it?). Here's what I see on load:

<img width="423" alt="screen shot 2016-09-17 at 9 31 35 pm" src="https://cloud.githubusercontent.com/assets/888422/18612905/2487da96-7d1e-11e6-8dfc-ce3e26858901.png">

@abyczkowska what do you think?

**Comment by abyczkowska** [comment]
I think it can be much smaller, it's there primarily to show that there is something loading. It'll be great to see it when it's 50px big.
