### ISSUE TITLE
Style tooltips

### ISSUE THREAD

**Issue by abyczkowska** [mbyczkowski/lacocina#46]
style the tooltips 
from:
<img width="151" alt="screen shot 2016-09-20 at 10 51 31 pm" src="https://cloud.githubusercontent.com/assets/4226378/18699243/e94de3b2-7f84-11e6-868a-babd9665df2f.png">
to:
<img width="150" alt="screen shot 2016-09-20 at 10 52 43 pm" src="https://cloud.githubusercontent.com/assets/4226378/18699252/f540ed90-7f84-11e6-82e4-c5cd7e84effd.png">

**Comment by katiemthom** [comment]
<img width="134" alt="screen shot 2016-10-02 at 9 48 58 am" src="https://cloud.githubusercontent.com/assets/4976125/19022131/7fae453c-8885-11e6-8126-dc6b4bdcaaa9.png">

How do you feel about this? Turns out that borders on tooltip triangles are kind of tricky...

**Comment by katiemthom** [comment]
(I can make it skinnier)

**Comment by katiemthom** [comment]
@abyczkowska
