### ISSUE TITLE
fix nav on 1024 px - 639 px

### ISSUE THREAD

**Issue by abyczkowska** [mbyczkowski/lacocina#47]
The menu disappears in between 1024px and 639px. 

At minimum we should show hamburger nav, otherwise it would be nice to get the donate be on the logo level with the other pages listed. 

I'll mock up something.

**Comment by mbyczkowski** [comment]
The mobile menu now shows up for medium size screens, so 640px to 1023px wide.

**Comment by mbyczkowski** [comment]
I don't know if we should bundle another nav layout issue here, but on screens that are 1024px or wider, the 'Donate' button is pushed down. We could play with padding, but in general, there's isn't much we can do (small padding causes menu items to appear as one almost), unless we make the font smaller, logo smaller, or come up with a better layout.

**This is what I get on MBP 15":**
<img width="1238" alt="screen shot 2016-09-25 at 10 58 06 pm" src="https://cloud.githubusercontent.com/assets/888422/18824015/f7a949c2-8373-11e6-8735-5c541b9c766b.png">

**Comment by abyczkowska** [comment]
yeah, I'll need to take a look at the nav, I'm afraid. Design changes tbd.

**Comment by abyczkowska** [comment]
the design for navigation on desktop is now updated in zeplin. Should be visible on tablet as well. Mobile nav needs to be styled

**Comment by mbyczkowski** [comment]
this got fixed after we updated the menu
<img width="1054" alt="screen shot 2016-11-17 at 10 53 31 pm" src="https://cloud.githubusercontent.com/assets/888422/20421432/a9370260-ad18-11e6-9a18-68a6fcfc610f.png">
