### ISSUE TITLE
Home page on mobile - hide content 

### ISSUE THREAD

**Issue by abyczkowska** [mbyczkowski/lacocina#49]
Implement the designs found in zeplin.
- don't display Bini's story and businesses

**Comment by katiemthom** [comment]
On tablets too?

**Comment by katiemthom** [comment]
@abyczkowska

**Comment by abyczkowska** [comment]
@katiemthom show on tablet. Photo added to dropbox. 

sorry, I've been looking more on slack than here and I missed A LOT!

**Comment by mbyczkowski** [comment]
@katiemthom I have added Bini's images to the repo for `medium` and `large` layouts
