### ISSUE TITLE
Make the tooltips clickable

### ISSUE THREAD

**Issue by abyczkowska** [mbyczkowski/lacocina#50]
The idea here is, that we want to be able to display the business name and link it to their website.
I'll get the websites from La Cocina leter, but let's set the ground for that work now.

**Comment by ghost** [comment]
I think we might need to find a new way to do tooltips. I'm pretty sure it's either that or we have to make some changes to foundation.tooltips.js

**Comment by mbyczkowski** [comment]
I figured how to show links in tooltips - #103

**Comment by mbyczkowski** [comment]
it's live now! :)
