### ISSUE TITLE
responsive banners

### ISSUE THREAD

**Issue by mbyczkowski** [mbyczkowski/lacocina#7]
We have images that span the width of the page, so they're pretty big, because we want them to look good on big screens. It would be cool if we could make them smaller on smaller screens (aka 'responsive images'). Foundation has something for this (but I never used it) - http://foundation.zurb.com/sites/docs/interchange.html

**Comment by mbyczkowski** [comment]
I think @abyczkowska can create appropriate images for various screen sizes (at least one for mobile where we should probably crop images to make them look taller without distorting them).

**Comment by ghost** [comment]
These are the specific interchange settings for quick reference:
<img width="739" alt="screen shot 2016-08-13 at 3 55 43 pm" src="https://cloud.githubusercontent.com/assets/15276915/17645292/269e9a06-616f-11e6-9487-a3d26bef0871.png">

**Comment by katiemthom** [comment]
This is related to issue #8 as well.

**Comment by abyczkowska** [comment]
Images added to dropbox folder (home_large, home_medium, home_small)
https://www.dropbox.com/home/La%20Cocina%20Assets/La%20Cocina%20Photos

**Comment by mbyczkowski** [comment]
This has been done, we just have use `responsive_image_tag` and then have 3 versions of each image `IMAGE_small`, `IMAGE_medium` and `IMAGE_large`.
