### ISSUE TITLE
Set-up Heroku SSL

### ISSUE THREAD

**Issue by mbyczkowski** [mbyczkowski/lacocina#99]
Since we added authentication and admin panel, we really need to get SSL set-up. SSL is available on Heroku for free for paid dynos. I think we'll have to figure how to use La Cocina's CC so we can start paying for our Heroku set-up.

**Comment by katiemthom** [comment]
@mbyczkowski, @abyczkowska volunteered you to get the CC info, so I'm assigning this to you for now.

**Comment by mbyczkowski** [comment]
I've got the CC info and got SSL set-up using Let's Encrypt and some custom code. We need to re-issues a cert when La Cocina switches the domain, but we're ready for this :)
